language: python
python:
  - "3.6"
before_install:
    - pip install pytest-cov
    - pip install coveralls
# command to install dependencies
install:
   -pip install -r requirements.txt
# command to run tests
services:
  - postgresql

before_script:
  - psql -c 'create database test_db;' -U postgres

script: py.test --cov=app tests/
after_success:
  - coveralls
